### ISSUE TITLE
java.nio.channels.ClosedChannelException on 

### ISSUE THREAD

**Issue by ffroliva** [making/rsc#28]
Hi, I am trying to test this websocket API using rsc but I keep on getting ClosedChannelException.

`java -jar rsc-0.5.0.jar wss://stream.binance.com:9443/ws/ethbtc@aggTrade --stream --stacktrace`

If I use this online tool with this same API it works. https://www.wss-websocket.net/

reactor.core.Exceptions$ReactiveException: java.nio.channels.ClosedChannelException
        at reactor.core.Exceptions.propagate(Exceptions.java:393)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
        at reactor.core.publisher.Flux.blockLast(Flux.java:2497)
        at am.ik.rsocket.Rsc.main(Rsc.java:84)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                ... 10 more
Caused by: java.nio.channels.ClosedChannelException

Any advice is appreciated.

**Comment by making** [comment]
I tried the same request with `--wiretap` option.

```
$ rsc wss://stream.binance.com:9443/ws/ethbtc@aggTrade --stream --wiretap
2020-09-09 04:47:26.134 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6] REGISTERED
2020-09-09 04:47:26.134 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6] CONNECT: stream.binance.com/54.65.27.89:9443
2020-09-09 04:47:26.155 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] ACTIVE
2020-09-09 04:47:26.163 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] READ COMPLETE
2020-09-09 04:47:26.171 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] READ COMPLETE
2020-09-09 04:47:26.177 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] USER_EVENT: SslHandshakeCompletionEvent(SUCCESS)
2020-09-09 04:47:26.177 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] WRITE: 264B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 47 45 54 20 2f 77 73 2f 65 74 68 62 74 63 40 61 |GET /ws/ethbtc@a|
|00000010| 67 67 54 72 61 64 65 20 48 54 54 50 2f 31 2e 31 |ggTrade HTTP/1.1|
|00000020| 0d 0a 75 73 65 72 2d 61 67 65 6e 74 3a 20 52 65 |..user-agent: Re|
|00000030| 61 63 74 6f 72 4e 65 74 74 79 2f 64 65 76 0d 0a |actorNetty/dev..|
|00000040| 61 63 63 65 70 74 3a 20 2a 2f 2a 0d 0a 68 6f 73 |accept: */*..hos|
|00000050| 74 3a 20 73 74 72 65 61 6d 2e 62 69 6e 61 6e 63 |t: stream.binanc|
|00000060| 65 2e 63 6f 6d 3a 39 34 34 33 0d 0a 75 70 67 72 |e.com:9443..upgr|
|00000070| 61 64 65 3a 20 77 65 62 73 6f 63 6b 65 74 0d 0a |ade: websocket..|
|00000080| 63 6f 6e 6e 65 63 74 69 6f 6e 3a 20 75 70 67 72 |connection: upgr|
|00000090| 61 64 65 0d 0a 73 65 63 2d 77 65 62 73 6f 63 6b |ade..sec-websock|
|000000a0| 65 74 2d 6b 65 79 3a 20 35 44 63 35 6a 4a 38 39 |et-key: 5Dc5jJ89|
|000000b0| 43 47 6c 66 58 68 30 30 36 39 45 35 46 41 3d 3d |CGlfXh0069E5FA==|
|000000c0| 0d 0a 6f 72 69 67 69 6e 3a 20 68 74 74 70 73 3a |..origin: https:|
|000000d0| 2f 2f 73 74 72 65 61 6d 2e 62 69 6e 61 6e 63 65 |//stream.binance|
|000000e0| 2e 63 6f 6d 3a 39 34 34 33 0d 0a 73 65 63 2d 77 |.com:9443..sec-w|
|000000f0| 65 62 73 6f 63 6b 65 74 2d 76 65 72 73 69 6f 6e |ebsocket-version|
|00000100| 3a 20 31 33 0d 0a 0d 0a                         |: 13....        |
+--------+-------------------------------------------------+----------------+
2020-09-09 04:47:26.177 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] FLUSH
2020-09-09 04:47:26.178 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] READ COMPLETE
2020-09-09 04:47:26.184 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] READ: 166B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 31 30 31 20 53 77 69 |HTTP/1.1 101 Swi|
|00000010| 74 63 68 69 6e 67 20 50 72 6f 74 6f 63 6f 6c 73 |tching Protocols|
|00000020| 0d 0a 44 61 74 65 3a 20 57 65 64 2c 20 30 39 20 |..Date: Wed, 09 |
|00000030| 53 65 70 20 32 30 32 30 20 30 34 3a 34 37 3a 32 |Sep 2020 04:47:2|
|00000040| 36 20 47 4d 54 0d 0a 43 6f 6e 6e 65 63 74 69 6f |6 GMT..Connectio|
|00000050| 6e 3a 20 75 70 67 72 61 64 65 0d 0a 55 70 67 72 |n: upgrade..Upgr|
|00000060| 61 64 65 3a 20 77 65 62 73 6f 63 6b 65 74 0d 0a |ade: websocket..|
|00000070| 53 65 63 2d 57 65 62 53 6f 63 6b 65 74 2d 41 63 |Sec-WebSocket-Ac|
|00000080| 63 65 70 74 3a 20 43 47 5a 69 6d 46 32 46 66 6d |cept: CGZimF2Ffm|
|00000090| 34 77 48 5a 5a 37 66 45 2b 33 61 68 6c 51 76 51 |4wHZZ7fE+3ahlQvQ|
|000000a0| 34 3d 0d 0a 0d 0a                               |4=....          |
+--------+-------------------------------------------------+----------------+
2020-09-09 04:47:26.185 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] WRITE: 52B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 82 ae 69 7a 20 37 69 7a 20 37 6d 7a 20 36 69 7a |..iz 7iz 7mz 6iz|
|00000010| 20 37 27 5a 20 36 36 ea 2a 43 0c 02 54 18 19 16 | 7'Z 66.*C..T...|
|00000020| 41 5e 07 6a 41 47 19 16 49 54 08 0e 49 58 07 55 |A^.jAG..IT..IX.U|
|00000030| 4a 44 06 14                                     |JD..            |
+--------+-------------------------------------------------+----------------+
2020-09-09 04:47:26.185 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] FLUSH
2020-09-09 04:47:26.185 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] READ COMPLETE
2020-09-09 04:47:26.191 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] READ: 19B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 88 11 03 f0 49 6e 76 61 6c 69 64 20 72 65 71 75 |....Invalid requ|
|00000010| 65 73 74                                        |est             |
+--------+-------------------------------------------------+----------------+
2020-09-09 04:47:26.191 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] WRITE: 23B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 88 91 59 70 3c 05 5a 80 75 6b 2f 11 50 6c 3d 50 |..Yp<.Z.uk/.Pl=P|
|00000010| 4e 60 28 05 59 76 2d                            |N`(.Yv-         |
+--------+-------------------------------------------------+----------------+
2020-09-09 04:47:26.191 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] FLUSH
2020-09-09 04:47:26.191 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 - R:stream.binance.com/54.65.27.89:9443] CLOSE
2020-09-09 04:47:26.192 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 ! R:stream.binance.com/54.65.27.89:9443] READ COMPLETE
2020-09-09 04:47:26.192 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 ! R:stream.binance.com/54.65.27.89:9443] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
2020-09-09 04:47:26.192 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 ! R:stream.binance.com/54.65.27.89:9443] INACTIVE
2020-09-09 04:47:26.192 DEBUG --- [ctor-http-nio-1] r.n.t.TcpClient : [id: 0x95bc03c6, L:/192.168.11.42:57941 ! R:stream.binance.com/54.65.27.89:9443] UNREGISTERED
Error: java.nio.channels.ClosedChannelException

Use --stacktrace option for details.
```

`Invalid request` is returned as you can see from the log. Maybe something is missing in the request?
Do you try the same request with Java API directly?

**Comment by making** [comment]
> If I use this online tool with this same API it works. https://www.wss-websocket.net/

It seems like `wss://stream.binance.com:9443/ws/ethbtc@aggTrade` is not a rsocket endpoint but a pure websocket endpoint.
`rsc` is not a websocket CLI but a rsocket CLI.

**Comment by ffroliva** [comment]
yes, you are correct. it is a simple websocket connection. In this case, do
I have to bridge this conection behind a rsocket server? Is it the approach
to go?

Em Qua, 9 de set de 2020 05:54, Toshiaki Maki <notifications@github.com>
escreveu:

**Comment by making** [comment]
Websocket is a transport layer under RSocket.
You need to implement your API with RSocket. 
If you are a Spring user, this blog post series are helpful.
https://spring.io/blog/2020/03/02/getting-started-with-rsocket-spring-boot-server

I'm closing this issue as this is not related to `rsc` itself.
